CREATE TABLE IF NOT EXISTS {table_name} (
    id VARCHAR,
    phone_n VARCHAR,
    operator VARCHAR,
    gender VARCHAR,
    age VARCHAR,
    age_group VARCHAR,
    location VARCHAR,
    location_type VARCHAR,
    usage_period VARCHAR,
    is_only_sim VARCHAR,
    sim2 VARCHAR,
    spendings VARCHAR,
    spending_range VARCHAR,
    occupation VARCHAR,
    education_lvl VARCHAR,
    has_kids VARCHAR,
    fin_state VARCHAR,
    date VARCHAR,
    wave VARCHAR,
    who_pays VARCHAR,
    weight VARCHAR,
    Q3_1_mob_int VARCHAR,
    Q1A VARCHAR,
    N01 VARCHAR
);