CREATE TABLE IF NOT EXISTS {table_name} (
    id INTEGER,
    phone_n INTEGER,
    operator VARCHAR,
    gender VARCHAR,
    age INTEGER,
    age_group VARCHAR,
    location VARCHAR,
    location_type VARCHAR,
    usage_period VARCHAR,
    is_only_sim VARCHAR,
    sim2 VARCHAR,
    spendings INTEGER,
    spending_range VARCHAR,
    occupation VARCHAR,
    education_lvl VARCHAR,
    has_kids VARCHAR,
    fin_state VARCHAR,
    date TIMESTAMP,
    wave VARCHAR,
    who_pays VARCHAR,
    weight NUMERIC,
    Q3_1_mob_int BYTEA,
    Q1A INTEGER,
    N01 INTEGER,
    insertion_date TIMESTAMP DEFAULT Now()
);