INSERT INTO {dst_table_name} (
	id,
    phone_n,
    operator,
    gender,
    age,
    age_group,
    location,
    location_type,
    usage_period,
    is_only_sim,
    sim2,
    spendings,
    spending_range,
    occupation,
    education_lvl,
    has_kids,
    fin_state,
    date,
    wave,
    who_pays,
    weight,
    Q3_1_mob_int,
    Q1A,
    N01)
SELECT 
	CAST(id AS INTEGER),
    CAST(phone_n AS INTEGER),
    operator,
    gender,
    CAST(age AS INTEGER),
    age_group,
    location,
    location_type,
    usage_period,
    is_only_sim,
    sim2,
    CAST(spendings AS INTEGER),
    spending_range,
    occupation,
    education_lvl,
    has_kids,
    fin_state,
    CAST(date AS TIMESTAMP),
    wave,
    who_pays,
    CAST(weight AS NUMERIC),
    CAST(Q3_1_mob_int AS BYTEA),
    CAST(Q1A AS INTEGER),
    CAST(N01 AS INTEGER)
FROM {src_table_name}
WHERE id<>'null';